/* 
Author: Fetch Cater
Date: 24/04/2024
Version: Finished Website
*/
$(function () {
    //this contains all the informaiton for the template to fill in the various id's with
    var bookTitles = [{ "title": "Black Paradox", "book": "black-paradox", "date": "October 25, 2022", "artandstory": "Art by Junji Ito <br> Story by Junji Ito", "blurb": "Four people intent on killing themselves meet through the suicide website Black Paradox: Maruso, a nurse who despairs about the future; Taburo, a man who is tortured by his doppelganger; Pii-tan, an engineer with his own robot clone; and Baracchi, a woman who agonizes about the birthmark on her face. They wander together in search of the perfect death, fatefully opening a door that leads them to a rather bizarre destiny…", "img": "img/books-black-paradox.png", "lengths": "208 pages", "isbn": "978-1-9747-2863-3", "chapters": "Group Suicide, A Strange Tale of the Pylorus, Paradoxical Night, Dr. Suka's Villa, The Spirit World Project, To The Dazzling Future, The Licking Woman (one-shot) and Mystery Pavillion (one-shot)", "background": "" },
    { "title": "Deserter", "book": "deserter", "date": "December 21, 2021", "artandstory": "Art by Junji Ito <br> Story by Junji Ito", "blurb": "A vengeful family hides an army deserter for eight years after the end of World War II, cocooning him in a false reality where the war never ended. A pair of girls look alike, but they’re not twins. And a boy’s nightmare threatens to spill out into the real world… This hauntingly strange story collection showcases a dozen of Junji Ito’s earliest works from when he burst onto the horror scene, sowing fresh seeds of terror.", "img": "img/books-deserter.png", "lengths": "392 pages", "isbn": "978-1-9747-1986-0", "chapters": "Bio House, Face Thief, Where the Sandman Lives, The Devil's Logic, The Long Hair in the Attic, Scripted Love, The Reanimator's Sword, A Father's Love, Unendurable Labyrinth, Village of the Siren, Bullied and Deserter", "background": "" },
    { "title": "Fragments of Horror", "book": "fragments", "date": "June 16, 2015", "artandstory": "Art by Junji Ito <br> Story by Junji Ito", "blurb": "A collection of delightfully macabre tales from a master of horror manga. An old wooden mansion that turns on its inhabitants. A dissection class with a most unusual subject. A funeral where the dead are definitely not laid to rest. Ranging from the terrifying to the comedic, from the erotic to the loathsome, these stories showcase Junji Ito’s long-awaited return to the world of horror.", "img": "img/books-fragments-of-horror.png", "lengths": "224 pages", "isbn": "978-1-4215-8079-1", "chapters": "Futon (Blanket), Haunted Wood Mansion, Tomio: Red Turtleneck, Lingering Farewell, Dissection Girl, Black Bird, Magami Nanakuse and Whispering Woman", "background": "" },
    { "title": "Frankenstein", "book": "frankenstein", "date": "October 16, 2018", "artandstory": "Art by Junji Ito <br> Story by Mary Shelley", "blurb": "Junji Ito meets Mary Shelley! The master of horror manga bends all his skill into bringing the anguished and solitary monster—and the fouler beast who created him—to life with the brilliantly detailed chiaroscuro he is known for. <br> Also included are six tales of Oshikiri—a high school student who lives in a decaying mansion connected to a haunted parallel world. Uncanny doppelgangers, unfortunately murdered friends, and a whole lot more are in store for him. Bonus: The Ito family dog! Thrill to the adventures of Non-non Ito, an adorable Maltese!", "img": "img/books-frankenstein.png", "lengths": "408 pages", "isbn": "978-1-9747-0376-0", "chapters": "Frankenstein, Neck Specter, Bog of Living Spirits, Pen Pal, Intruder, The Strange Tale of Oshikiri, The Strange Tale of Oshikiri: The Walls, The Hell of the Doll Funeral, Face Firmly in Place and Nonnon Oyabun", "background": "This book is Junji Ito's adaptation of Mary Shelley's book titles Frankenstein" },
    { "title": "Gyo (2-In-1 Deluxe Edition)", "book": "gyo-deluxe", "date": "April 21, 2015", "artandstory": "Art by Junji Ito <br> Story by Junji Ito", "blurb": "The floating smell of death hangs over the island. What is it? A strange, legged fish appears on the scene... So begins Tadashi and Kaori's spiral into the horror and stench of the sea. Here is the creepiest masterpiece of horror manga ever from the creator of Uzumaki, Junji Ito. Hold your breath until all is revealed. Something's rotten in Okinawa...", "img": "img/books-gyo-2-in-1-deluxe-edition.png", "lengths": "400 pages", "isbn": "978-1-4215-7915-3", "chapters": "The Death-Stench of the South Seas, The Death Stench In The Air, Going Ashore, Shark Attack, Flight, The Death Stench Creeps, Testimony, Infection, The Death Stench Invades (Part 2), Pale Kaori, The Death Stench Devices, The Inheritors, The Pull Of The Death Stench, The Death Stench Circus (Part 1), The Death Stench Circus (Part 2), The Death Stench Of Lab No 2, The Death Stench Air Raid and The Death Stench World", "background": "Gyo 2-in-1 Deluxe Edition combines Junji Ito's pervious 2 book series,Gyo, Vol. 1 and Gyo, Vol. 2: The Death-Stench, Gyo was influenced by his childhood anti-war feelings, due to his parents' tragic and frightening war stories, and the shark attack scenes from Jaws." },
    { "title": "Gyo, Vol. 1", "book": "gyo-1", "date": "October 16, 2007", "artandstory": "Art by Junji Ito <br> Story by Junji Ito", "blurb": "Horror under the waves; The Stench of the Sea… & Horror by the Seaside… Something is rotten in Okinawa...the floating stench of death hangs over the island..What is it? A strange, legged fish appears on the scene...so begins Tadashi and Kaori's spiral into the horror (and stench) of the sea. Here is the long-awaited new horror manga series from the Eisner-nominated creator of Uzumaki, Junji Ito. Something’s Rotten in Okinawa… The rank odor of death floats above the famous island… What is the source? Then a strange fish—with legs—appears! So begins teenagers Tadashi and Kaori’s plunge into the horror (and stench) of the sea.", "img": "img/books-gyo-vol-1.png", "lengths": "200 pages", "isbn": "978-1421513874", "chapters": "The Death-Stench of the South Seas, The Death Stench In The Air, Going Ashore, Shark Attack, Flight, The Death Stench Creeps, Testimony and Infection", "background": "" },
    { "title": "Gyo, Vol. 2: The Death-Stench", "book": "gyo-2", "date": "January 15, 2008", "artandstory": "Art by Junji Ito <br> Story by Junji Ito", "blurb": "Horror under the waves; The Stench of the Sea… & Horror by the Seaside… Something is rotten in Okinawa...the floating stench of death hangs over the island..What is it? A strange, legged fish appears on the scene...so begins Tadashi and Kaori's spiral into the horror (and stench) of the sea. Here is the long-awaited new horror manga series from the Eisner-nominated creator of Uzumaki, Junji Ito. The Horrifying Conclusion… Trapped on an island filled with the stench of mutating bodies, can teenager Tadashi save his girlfriend from a fate worse than death? Or will the cure prove worse than the disease? Hold your breath until all is revealed—along with the final stinking secrets of the “walking fish of Okinawa”!", "img": "img/books-gyo-vol-2.png", "lengths": "208 pages", "isbn": "978-1421513881", "chapters": "The Death Stench Invades (Part 2), Pale Kaori, The Death Stench Devices, The Inheritors, The Pull Of The Death Stench, The Death Stench Circus (Part 1), The Death Stench Circus (Part 2), The Death Stench Of Lab No 2, The Death Stench Air Raid and The Death Stench World", "background": "" },
    { "title": "Junji Ito Collection: A Horror Coloring", "book": "collection-coloring", "date": "August 1, 2022", "artandstory": "Art by Junji Ito", "blurb": "Explore the macabre mind of Japan's master of horror, Junji Ito, in this chilling adult colouring book. The Junji Ito Collection Colouring Book is the perfect gift for fans of manga's master of the macabre. This officially licensed compendium features dozens of terrifying scenes from Junji Ito Collection to colour, showcasing Ito's uniquely twisted brand of horror. Ghosts, demons, monsters and more await your pencils inside!", "img": "img/books-junji-ito-collection-coloring-book.png", "lengths": "80 pages", "isbn": "9781789099720", "chapters": "", "background": "" },
    { "title": "Junji Ito's Cat Diary: Yon & Mu", "book": "cat-diary", "date": "November 9, 2021", "artandstory": "Art by Junji Ito <br> Story by Junji Ito", "blurb": "Is there anything spookier than a silent feline, eyes glinting, stalking you in the night...IN YOUR OWN HOME Master of horror Junji Ito turns his twisted eye on his own life in this comedic graphic memoir about becoming a cat owner, now reissued in a deluxe hardcover featuring an exclusive interivew with Ito and a NEW cover illustration by the author that GLOWS IN THE DARK! The perfect gift for the slightly-twisted cat lover in your life. Reigning king of horror manga Junji Ito presents a series of hissterical tales chronicling his real-life trials and tribulations of becoming a cat owner. Junji Ito, as J-kun, has recently built a new house and has invited his financée, A-ko, to live with him. Little did he know...his blushing bride-to-be has some unexpected company in tow--Yon, a ghastly-looking family cat, and Mu, an adorable Norwegian forest cat. Despite being a dog person, J-kun finds himself purrsuaded by their odd cuteness and thus begins his comedic struggle to gain the affection of his new feline friends.", "img": "img/books-junji-itos-cat-diary.png", "lengths": "128 pages", "isbn": "9781646512515", "chapters": "Muu shows up, Yon attacks, Cat wand battle!, The happenings of a certain night, Yon really is a strange cat, Yon’s great escape, King Yon, Muu’s castration, Unidentified organizm and Without stepping on poop, mucus, or cats", "background": "" },
    { "title": "Junji Ito's Dissolving Classroom", "book": "dissolving-classrooms", "date": "31 January, 2017", "artandstory": "Art by Junji Ito <br> Story by Junji Ito", "blurb": "A new collection of horrific tales from the master of Japanese horror manga, Junji Ito. Detailing the depths at which a teen will go to get revenge on the world, Dissolving Classroom is J-Horror at its most beatifully grotesque. Teenager Yuma Azawa transfers to a new high school but something strange seems to have followed him there. Is it a curse? Or is he cursing those who have been putting him down? Dissolving Classroom collects seven new short horror stories from Japan's master of horror comics Junji Ito.", "img": "img/books-junji-itos-dissolving-classroom.png", "lengths": "178 pages", "isbn": "978-1942993858", "chapters": "Dissolving Classroom, Dissolving Beauty, Dissolving Apartment, Chizumi in Love and Interview with the Devil", "background": "" },
    { "title": "Lovesickness", "book": "lovesickness", "date": "April 20, 2021", "artandstory": "Art by Junji Ito <br> Story by Junji Ito", "blurb": "Ryusuke returns to the town he once lived in because rumors are swirling about girls killing themselves after encountering a bewitchingly handsome young man. Harboring his own secret from time spent in this town, Ryusuke attempts to capture the beautiful boy and close the case, but… Starting with the strikingly bloody “Lovesickness,” this volume collects ten stories showcasing horror master Junji Ito in peak form, including “The Strange Hikizuri Siblings” and “The Rib Woman.”", "img": "img/books-lovesickness.png", "lengths": "408 pages", "isbn": "978-1-9747-1984-6", "chapters": "The Beautiful Boy at the Crossroads, A Woman in Distress, Shadow, Screams in the Night, The Boy in White, The Strange Hikizuri Siblings: Narumi's Boyfriend, The Strange Hikizuri Siblings: The Séance, The Mansion of Phantom Pain, The Rib Woman and Memories of Real Poop", "background": "" },
    { "title": "Mimi's Tales of Terror", "book": "mimi", "date": "October 24, 2023", "artandstory": "Art by Junji Ito <br> Story by Hirokatsu Kihara and Ichiro Nakayama", "blurb": "University student Mimi and her boyfriend Naoto encounter one chilling mystery after another. There’s the enigmatic neighbor woman dressed in black from head to toe—but if she’s so odd, why does it seems like there are many others like her? Then, whose eyes track Mimi’s movements from the cemetery next door? And why does a bizarre red circle drawn on a basement wall change with each passing day? Nine scary stories that really happened, drawn from the famed collecton of urban legends Shin Mimibukuro (New Earmuffs), and adapted into manga by horror genius Junji Ito!", "img": "img/books-mimis-tales-of-terror.png", "lengths": "224 pages", "isbn": "978-1-9747-3851-9", "chapters": "On the Utility Pole, The Woman Next Door, Rustling in the Grass, Seashore, Just the Two of Us, Scarlet Circle, Sign in the Field, Mimi's Tales of Terror Afterword and Monster Prop (oneshot)", "background": "" },
    { "title": "No Longer Human", "book": "no-longer-human", "date": "December 17, 2019", "artandstory": "Art by Junji Ito <br> Story by Osamu Dazai", "blurb": "Mine has been a life of much shame. I can’t even guess myself what it must be to live the life of a human being. Plagued by a maddening anxiety, the terrible disconnect between his own concept of happiness and the joy of the rest of the world, Yozo Oba plays the clown in his dissolute life, holding up a mask for those around him as he spirals ever downward, locked arm-in-arm with death. Osamu Dazai’s immortal—and supposedly autobiographical—work of Japanese literature, is perfectly adapted here into a manga by Junji Ito. The imagery wrenches open the text of the novel one line at a time to sublimate Yozo’s mental landscape into something even more delicate and grotesque. This is the ultimate in art by Ito, proof that nothing can surpass the terror of the human psyche.", "img": "img/books-no-longer-human.png", "lengths": "616 pages", "isbn": "978-1-9747-0709-6", "chapters": "Yozo Oba, Clown, The Human Female, Good for Nothing, Outcast, Tsuneko, Paradise, Cold Sweat, Toad, Chance Meeting, An Unexpected Visitor, Fleeting Glory, Tragicomic, Aspects of Human Behavior, The Deepest Hell, Spellbound, Hiroko, Heaven and Hell, Doubt, Obsession, No Longer Human, Real Name, Comedy and Everything Passes", "background": "" },
    { "title": "Remina", "book": "remina", "date": "December 15, 2020", "artandstory": "Art by Junji Ito <br> Story by Junji Ito", "blurb": "An unknown planet emerges from inside a wormhole, and its discoverer, Dr. Oguro, christens the body “Remina” after his own daughter. His finding is met with great fanfare, and Remina herself rises to fame. However, the object picks up speed as it moves along in its curious course, eliminating planets and stars one after another, until finally Earth itself faces extinction… Is the girl Remina the true cause of the catastrophe? A masterwork of horror from Junji Ito, unfolding on a universal scale.", "img": "img/books-remina.png", "lengths": "256 pages", "isbn": "978-1-9747-1747-7", "chapters": "Vile Star, Girl Hunting, Plague, Tongue's Shadow, Licking Planet and Endless Void", "background": "" },
    { "title": "Sensor", "book": "sensor", "date": "August 17, 2021", "artandstory": "Art by Junji Ito <br> Story by Junji Ito", "blurb": "A woman walks alone at the foot of Mount Sengoku. A man appears, saying he’s been waiting for her, and invites her to a nearby village. Surprisingly, the village is covered in hairlike volcanic glass fibers, and all of it shines a bright gold. At night, when the villagers perform their custom of gazing up at the starry sky, countless unidentified flying objects come raining down on them—the opening act for the terror about to occur!", "img": "img/books-sensor.png", "lengths": "240 pages", "isbn": "978-1-9747-1890-0", "chapters": "Angel Hair, Akashic Records, Hypnotherapy, Battle at Bishagaura, Traffic Mirror, Jet-Black and Light and Dark", "background": "" },
    { "title": "Shiver: Junji Ito Selected Stories", "book": "shiver", "date": "December 19, 2017", "artandstory": "Art by Junji Ito <br> Story by Junji Ito", "blurb": "An arm peppered with tiny holes dangles from a sick girl’s window… After an idol hangs herself, balloons bearing the faces of their destined victims appear in the sky… An amateur film crew hires an extremely individualistic fashion model and faces a real bloody ending… An offering of nine fresh nightmares for the delectation of horror fans.", "img": "img/books-shiver.png", "lengths": "400 pages", "isbn": "978-1-4215-9693-8", "chapters": "Used Record, Shiver, Fashion Model, Hanging Blimp, Marionette Mansion, Painter, The Long Dream, Honored Ancestors, Greased and Fashion Model: Cursed Frame", "background": "" },
    { "title": "Smashed: Junji Ito Story Collection", "book": "smashed", "date": "April 16, 2019", "artandstory": "Art by Junji Ito <br> Story by Junji Ito", "blurb": "Try not to be noticed when you eat the secret nectar, otherwise you’ll get smashed… What horrific events happened to create the earthbound—people tied to a certain place for the rest of their short lives? Then, a strange haunted house comes to town, but no one expects it to lead to a real hell… Welcome to Junji Ito’s world, a world with no escape from endless nightmares.", "img": "img/books-smashed.png", "lengths": "416 pages", "isbn": "978-1-4215-9846-8", "chapters": "Bloodsucking Darkness, Ghosts of Prime Time, Roar, Earthbound, Death Row Doorbell, The Mystery of the Haunted House, The Mystery of the Haunted House: Soichi's Version, Soichi's Beloved Pet, In Mirror Valley, I Don't Want to be a Ghost, Library Vision, Splendid Shadow Song and Smashed", "background": "" },
    { "title": "Soichi: Junji Ito Story Collection", "book": "soichi", "date": "July 25, 2023", "artandstory": "Art by Junji Ito <br> Story by Junji Ito", "blurb": "“I’ll get you for this… I’ll show you true horror!” Soichi, the unhinged second son of the Tsujii family, chews nails and makes them clatter and clack as he spouts horrific curses to bring about the most bizarre happenings. Whether it’s summer holidays or a birthday party, Soichi can turn any occasion into a nightmare in a heartbeat. What is the terrible secret of his origin? Meanwhile, tormented by his little brother’s never-ending pranks, older brother Koichi has a soundproof room built. But why does it have a series of four doors? And then there’s the strange phenomenon surrounding the handmade casket their grandfather left behind. What on earth—or hell—has the family seen there? Ten tales that celebrate the sinister and hilarious world of Junji Ito’s favorite antihero, Soichi!", "img": "img/books-soichi.png", "lengths": "416 pages", "isbn": "978-1-9747-3902-8", "chapters": "A Happy Summer Vacation, A Happy Winter Vacation, Souichi's Happy Diary, Souichi's Home Visit, Teacher of Cloth, Souichi's Birthday, Souichi's Petty Curses, Four-Layered Room, Coffin and Rumors", "background": "" },
    { "title": "Stitches", "book": "stitches", "date": "March 26, 2024", "artandstory": "Art by Junji Ito <br> Story by Hirokatsu Kihara", "blurb": "A tumor shaped like a man’s face slowly moves across a woman’s body. The sea shoots glowing balls into the sky, much to the distress of beachgoers. And a girl dressed up for a holiday has no eyes, no nose, nothing—her face is a total blank. Hirokatsu Kihara pens true stories of unsolved mysteries, stitched together with page after page of Junji Ito’s original illustrations in this collection of nine eerie tales and a bonus manga story.", "img": "img/books-stitches.png", "lengths": "112 pages", "isbn": "978-1-9747-3656-0", "chapters": "", "background": "" },
    { "title": "The Art of Junji Ito: Twisted Visions", "book": "twisted-visions", "date": "April 21, 2020", "artandstory": "Art by Junji Ito", "blurb": "A first-ever collection of Junji Ito’s artworks, featuring over 130 images from his bestselling manga titles along with rare works. This sublime collection includes all of Ito’s unforgettable illustrations in both black-and-white and color, from Tomie’s dreadful beauty to the inhuman spirals of Uzumaki. Includes an interview focused on Ito’s art technique as well as commentary from the artist on each work.", "img": "img/books-the-art-of-junji-ito-twisted-visions.png", "lengths": "150 pages", "isbn": "978-1-9747-1300-4", "chapters": "", "background": "" },
    { "title": "The Liminal Zone", "book": "liminal-zone", "date": "July 26, 2022", "artandstory": "Art by Junji Ito <br> Story by Junji Ito", "blurb": "What destiny awaits them after the screaming? After abruptly departing from a train in a small town, a couple encounters a “weeping woman”—a professional mourner—sobbing inconsolably at a funeral. Mako changes afterward—she can’t stop crying! In another tale, having decided to die together, a couple enters Aokigahara, the infamous suicide forest. What is the shocking otherworldly torrent that they discover there? One of horror’s greatest talents, Junji Ito beckons readers to join him in an experience of ultimate terror with four transcendently terrifying tales.", "img": "img/books-the-liminal-zone.png", "lengths": "216 pages", "isbn": "978-1-9747-2644-8", "chapters": "Weeping Woman Way, Madonna, The Spirit Flow of Aokigahara and Slumber", "background": "" },
    { "title": "Tombs", "book": "tombs", "date": "March 28, 2023", "artandstory": "Art by Junji Ito <br> Story by Junji Ito", "blurb": "Countless tombstones stand in rows throughout a small community, forming a bizarre tableau. What fate awaits a brother and sister after a traffic accident in this town of the dead? In another tale, a girl falls silent, her tongue transformed into a slug. Can a friend save her? Then, when a young man moves to a new town, he finds the house next door has only a single window. What does his grotesque neighbor want, calling out to him every evening from that lone window? Fresh nightmares brought to you by horror master Junji Ito.", "img": "img/books-tombs.png", "lengths": "344 pages", "isbn": "978-1-9747-3604-1", "chapters": "Tombs, Clubhouse, Slug Girl, The Window Next Door, Washed Ashore, The Strange Tale of the Tunnel, Bronze Statue, Floaters and The Bloody Story of Shirosuna", "background": "" },
    { "title": "Tomie: Complete", "book": "tomie-deluxe", "date": "December 20, 2016", "artandstory": "Art by Junji Ito <br> Story by Junji Ito", "blurb": "Tomie Kawakami is a femme fatale with long black hair and a beauty mark just under her left eye. She can seduce nearly any man, and drive them to murder as well, even though the victim is often Tomie herself. While one lover seeks to keep her for himself, another grows terrified of the immortal succubus. But soon they realize that no matter how many times they kill her, the world will never be free of Tomie.", "img": "img/books-tomie-complete.png", "lengths": "752 pages", "isbn": "978-1-4215-9056-1", "chapters": "Tomie, Tomie Part 2,Basement, Photograph, Kiss, Mansion, Revenge, The Basin of the Waterfall, Painter, Museum of Terror 2, Murder, Hair, Orphan Girl, Little Finger, Boy, Moromi, Babysitter, Gathering, Passing Demon, Top Model and Old and Ugly", "background": "Tomie was inspired by the death of one of his classmates. Ito felt strange that a boy he knew suddenly disappeared from the world, and he kept expecting the boy to show up again; from this came the idea of a girl who is supposed to have died but then just shows up as if nothing had happened." },
    { "title": "Uzumaki (3-In-1 Deluxe Edition)", "book": "uzumaki-deluxe", "date": "October 15, 2013", "artandstory": "Art by Junji Ito <br> Story by Junji Ito", "blurb": "Kurouzu-cho, a small fogbound town on the coast of Japan, is cursed. According to Shuichi Saito, the withdrawn boyfriend of teenager Kirie Goshima, their town is haunted not by a person or being but a pattern: UZUMAKI, the spiral—the hypnotic secret shape of the world. The bizarre masterpiece horror manga is now available all in a single volume. Fall into a whirlpool of terror!", "img": "img/books-uzumaki-3-in-1-deluxe-edition.png", "lengths": "648 pages", "isbn": "978-1-4215-6132-5", "chapters": "The Spiral Obsession: Part 1, The Spiral Obsession: Part 2, The Scar, The Firing Effect, Twisted Souls, Medusa, Jack-in-the-Box, The Snail, The Black Lighthouse, Mosquitoes, The Umbilical Cord, The Storm, The House, Butterflies, Chaos, Erosion, Escape, The Labyrinth, Completion, Lost Chapter: Galaxies", "background": "" },
    { "title": "Uzumaki Coloring Book", "book": "uzumaki-coloring", "date": "March 15, 2022", "artandstory": "Art by Junji Ito", "blurb": "SPIRALS… THIS TOWN IS CONTAMINATED WITH SPIRALS… Kurouzu-cho, a small fogbound town on the coast of Japan, is haunted not by a person or being but a pattern: Uzumaki, the spiral—the hypnotic secret shape of the world. The bizarre masterpiece of horror manga, Uzumaki by Junji Ito, has been transformed into coloring book format. Color in each detail of the spirals and you may fall into a whirlpool of terror, never to escape!", "img": "img/books-uzumaki-coloring-book.png", "lengths": "80 pages", "isbn": "978-1-9747-2839-8", "chapters": "", "background": "" },
    { "title": "Uzumaki, Volume 1", "book": "uzumaki-1", "date": "October 16, 2007", "artandstory": "Art by Junji Ito <br> Story by Junji Ito", "blurb": "Shortly after Shuichi Saito's father becomes obsessed with spiral patterns, he dies mysteriously, his body positioned in the shape of a twisted coil, and soon the entire town is afflicted with a snail-like disease.", "img": "img/books-uzumaki-vol-1.png", "lengths": "208 pages", "isbn": "9781421513898", "chapters": "The Spiral Obsession: Part 1, The Spiral Obsession: Part 2, The Scar, The Firing Effect, Twisted Souls and Medusa", "background": "" },
    { "title": "Uzumaki, Volume 2", "book": "uzumaki-2", "date": "December 18, 2007", "artandstory": "Art by Junji Ito <br> Story by Junji Ito", "blurb": "Kurôzu-cho, a small fogbound town on the coast of Japan, is cursed. But the spirit which haunts it does not have a name or a body, only a shape: uzumaki the spiral, the hypnotic secret shape of the world.", "img": "img/books-uzumaki-vol-2.png", "lengths": "	208 pages", "isbn": " 9781421513904", "chapters": "Jack-in-the-Box, The Snail, The Black Lighthouse, Mosquitoes, The Umbilical Cord and The Storm", "background": "" },
    { "title": "Uzumaki, Volume 3", "book": "uzumaki-3", "date": "February 19, 2008", "artandstory": "Art by Junji Ito <br> Story by Junji Ito", "blurb": "With their town devastated by titanic hurricanes, the citizens of the spiral-haunted town of Kurôzu-cho--including Shuichi, Kirie and her family--find themselves cut off from the outside world. Reporters and rescue teams cross the mountain range into Kurôzu-cho only to find themselves unable to leave. Trapped inside the cursed ruins, the desperate survivors struggle and huddle together, waiting to run into giant snails or worse. The very laws of nature are changed as the spiral sucks them in. And to fight it, or to escape, the last survivors must go to the heart of the horror to witness what may be their evenutal fate...", "img": "img/books-uzumaki-vol-3.png", "lengths": "264 pages", "isbn": "978-1421513911", "chapters": "The House, Butterflies, Chaos, Erosion, Escape, The Labyrinth, Completion and Lost Chapter: Galaxies", "background": "" },
    { "title": "Venus in the Blind Spot", "book": "venus", "date": "August 18, 2020", "artandstory": "Art by Junji Ito <br> Story by Junji Ito", "blurb": "This striking collection presents the most remarkable short works of Junji Ito’s career, featuring an adaptation of Rampo Edogawa’s classic horror story “Human Chair” and fan favorite “The Enigma of Amigara Fault.” With a deluxe presentation—including special color pages, and showcasing illustrations from his acclaimed long-form manga No Longer Human—each chilling tale invites readers to revel in a world of terror.", "img": "img/books-venus-in-the-blind-spot.png", "lengths": "272 pages", "isbn": "978-1-9747-1547-3", "chapters": "Billions Alone, The Human Chair, An Unearthly Love, Venus in the Blind Spot, The Licking Woman, Master Umezz and Me, How Love Came to Professor Kirida, The Enigma of Amigara Fault, The Sad Tale of the Principal Post and Keepsake", "background": "" }]

    //this list of variables set up the ability to connect the information with the relevant points on the page
    var title = document.getElementById("title")
    var date = document.getElementById("date")
    var artAndStory = document.getElementById("artandstory")
    var blurb = document.getElementById("blurb")
    var img = document.getElementById("img")
    var lengths = document.getElementById("lengths")
    var isbn = document.getElementById("isbn")
    var chapters = document.getElementById("chapters")
    var background = document.getElementById("background")


    //URL parameters let me get the parameters in the url, aligning with the other javascript page where there is a book attribute next to the title attributes at the top of the page https://www.sitepoint.com/get-url-parameters-with-javascript/
    var queryString = window.location.search
    //this takes off the beginning of the url parameters, using slice to take off the first x amount of charecters off
    queryString = queryString.slice(12)
    var book = ""

    //this loop goes through all the book titles until it finds the one it matches, where it sets the book to e
    for (let i = 0; i < bookTitles.length; i++) {
        const e = bookTitles[i];
        if (e.book == queryString) {
            book = e
            break;
        }
    }

    //this sets the inner html to the corresponding key value pairs, except for the img where i set the attrubute to src to link the appropriate img
    title.innerHTML = book.title
    date.innerHTML = book.date
    artAndStory.innerHTML = book.artandstory
    blurb.innerHTML = book.blurb
    img.setAttribute("src", book.img)
    lengths.innerHTML = book.lengths
    isbn.innerHTML = book.isbn
    chapters.innerHTML = book.chapters
    background.innerHTML = book.background

    //this removes the chapters and background content if there is no information inputed into the value of the key 
    if (book.chapters == "") {
        chapters.parentNode.parentNode.removeChild(chapters.parentNode);
    }

    if (book.background == "") {
        background.parentNode.parentNode.removeChild(background.parentNode);
    }
})